version: '3'
services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - 3306:3306 # Port mapping port:host
    environment: # Environment variables for mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica_db
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=master_replica_db # master id= 1 because is the master
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    ports:
      - 3307:3306 # Port mapping port:host
    environment: # Environment variables for mysql slave
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica_db # debe ser el mismo nombre del master
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=master_replica_db # slave id= 2 because is the slave
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin01
    ports:
      - 8080:80 # Port mapping port:host
    environment: # names of the mysql containers to connect to phpmyadmin
      PMA_HOST: "mysql-master,mysql-slave"
      PMA_ARBITRARY: 1 # Allow arbitrary server
